#**************************************************************************
# Author: Matsumoto
# Date: 2024/09/06
#
# Lightsail:   WordPressServer
#**************************************************************************
AWSTemplateFormatVersion: 2010-09-09

Resources:
  
  #**************************************************************************
  # Lightsail Section
  #**************************************************************************
  WordPressServer: 
    Type: AWS::Lightsail::Instance
    Properties:
      BlueprintId: wordpress
      BundleId: nano_2_0
      InstanceName: WordPressServer

  WordPressIp:
    Type: AWS::Lightsail::StaticIp
    Properties: 
      AttachedTo: WordPressServer
      StaticIpName: WordPressIp

Outputs:
  WordPressIp:
    Description: WordPressIp
    Value: !GetAtt WordPressIp.IpAddress
